<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>AbsoluteStraftatController</AssemblyName>
    <RootNamespace>AbsoluteStraftat.Controller</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" PrivateAssets="all" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" PrivateAssets="all" />
  </ItemGroup>

</Project>
